"""Repository contracts for tenant-owned RecordGuard operations."""
from typing import Protocol, Optional

class OperationsRepository(Protocol):
    # patient linking
    def request_patient_link(self, actor, patient_id: str, reason: str = ""): ...
    def review_patient_link_request(self, actor, request_id: str, decision: str, notes: str = ""): ...
    def list_patient_link_requests(self, actor, status: Optional[str] = None): ...
    # family
    def create_family_relationship(self, actor, patient_id: str, related_patient_id: str, relationship_type: str): ...
    def list_family_relationships(self, actor, patient_id: str): ...
    def grant_family_access(self, actor, patient_id: str, grantee_user_id: str, resource_type: str, permission: str): ...
    def revoke_family_access(self, actor, grant_id: str): ...
    def list_family_access(self, actor, patient_id: str): ...
    # sharing
    def create_record_shares_batch(self, actor, patient_id: str, items, shared_with: str, expires_at=None): ...
    def list_record_shares(self, actor, patient_id: str): ...
    def revoke_record_share(self, actor, share_id: str): ...
    # attachments
    def add_attachment(self, actor, patient_id: str, source_path: str, encounter_id=None, record_id=None): ...
    def list_attachments(self, actor, patient_id: str): ...
    # lifecycle
    def lifecycle_medication(self, actor, record_id: str, action: str, password: Optional[str] = None): ...
    def lifecycle_ehr(self, actor, resource_type: str, resource_id: str, action: str, password: Optional[str] = None): ...
