"""Repository contracts for RecordGuard's database-independent services."""
from typing import Protocol, Optional


class SessionRepository(Protocol):
    def create_session(self, user_id: int, organization_id: str, ttl_seconds: int = 3600) -> str: ...
    def get_session_user(self, token: str) -> Optional[dict]: ...
    def revoke_session(self, token: str) -> None: ...
