"""Run the final RecordGuard validation gates without pretending missing environments passed."""
from __future__ import annotations
import json, os, shutil, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / 'apps' / 'web'

def run(cmd, cwd=ROOT, timeout=180):
    try:
        p = subprocess.run(cmd, cwd=cwd, text=True, capture_output=True, timeout=timeout)
        return p.returncode == 0, (p.stdout + p.stderr).strip()[-4000:]
    except FileNotFoundError:
        return False, 'command not found'
    except subprocess.TimeoutExpired:
        return False, f'timed out after {timeout}s'

def main():
    results = []
    ok, out = run([sys.executable, '-m', 'compileall', '-q', '.'])
    results.append({'gate':'python_compile','status':'PASS' if ok else 'FAIL','detail':out})
    ok, out = run([sys.executable, '-m', 'pytest', '-q'], timeout=300)
    results.append({'gate':'python_regression','status':'PASS' if ok else 'FAIL','detail':out})
    postgres = bool(os.getenv('RECORDGUARD_DATABASE_URL')) and os.getenv('RECORDGUARD_SESSION_BACKEND','').lower() == 'postgres'
    results.append({'gate':'postgres_live_configuration','status':'PASS' if postgres else 'BLOCKED','detail':'PostgreSQL DSN + postgres session backend required'})
    environment = os.getenv('RECORDGUARD_ENV','development').strip().lower()
    origins = [x.strip() for x in os.getenv('RECORDGUARD_WEB_ORIGINS','').split(',') if x.strip()]
    if environment == 'production':
        valid_origins = bool(origins) and all(o.lower().startswith('https://') and o != '*' for o in origins)
        results.append({'gate':'production_web_origins','status':'PASS' if valid_origins else 'BLOCKED','detail':','.join(origins) if valid_origins else 'production requires explicit HTTPS origins'})
    else:
        results.append({'gate':'production_web_origins','status':'PASS' if origins else 'BLOCKED','detail':','.join(origins) if origins else 'explicit origins required'})
    node = shutil.which('node'); npm = shutil.which('npm')
    results.append({'gate':'node_npm','status':'PASS' if node and npm else 'BLOCKED','detail':f'node={node or "missing"}, npm={npm or "missing"}'})
    installed = (WEB / 'node_modules').is_dir() and (WEB / 'node_modules' / 'next').exists()
    if installed:
        ok, out = run(['npm','run','build'], cwd=WEB, timeout=300)
        results.append({'gate':'next_production_build','status':'PASS' if ok else 'FAIL','detail':out})
    else:
        results.append({'gate':'next_production_build','status':'BLOCKED','detail':'apps/web/node_modules/next is not installed'})
    audit = shutil.which('pip-audit')
    if audit:
        ok, out = run([audit,'-r','requirements.txt','-r','requirements-web.txt'], timeout=300)
        results.append({'gate':'dependency_audit','status':'PASS' if ok else 'FAIL','detail':out})
    else:
        results.append({'gate':'dependency_audit','status':'BLOCKED','detail':'pip-audit is not installed'})
    report = ROOT / 'FINAL_VALIDATION_REPORT.md'
    lines = ['# RecordGuard Final Validation Report','','Generated by `scripts/final_validation.py`.','']
    for r in results:
        lines += [f"## {r['gate']}", f"**{r['status']}**", '', '```text', r['detail'] or '(no output)', '```', '']
    unresolved = sum(r['status'] in {'BLOCKED','FAIL'} for r in results)
    lines += [f'## Overall', '', '**READY**' if unresolved == 0 else f'**NOT RELEASE-READY — {unresolved} gate(s) unresolved**', '']
    report.write_text('\n'.join(lines), encoding='utf-8')
    (ROOT / 'FINAL_VALIDATION_RESULTS.json').write_text(json.dumps(results, indent=2), encoding='utf-8')
    print('\n'.join(f"{r['status']:7} {r['gate']}" for r in results))
    return 0 if unresolved == 0 else 2

if __name__ == '__main__':
    raise SystemExit(main())
